@echo off
echo Starting Backend...
start "Backend" cmd /k "cd backend && call venv\Scripts\activate && python -m uvicorn app.main:app --reload"
echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm run dev"
echo All services started.
