"""create_features_and_why_tables

Revision ID: 1150aeaada0c
Revises: cbc2e15fddc2
Create Date: 2026-01-23 18:47:48.930694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1150aeaada0c'
down_revision: Union[str, None] = 'cbc2e15fddc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
